### ISSUE TITLE
Smooth Switch between HTML5 and Flash

### ISSUE THREAD

**Issue by Cheedoong** [ViewCloud/GPlayer#2]
It can be counted that video.js hooks the `<video>` tag. 
As we know, 

> Any problem in computer science can be solved by another layer of indirection. 

So the switching problem between HTML5 and Flash can be solved by adding another layer? (handler of different types of virtual `<video>`s)

**Comment by moJiXiang** [comment]
`video.js` has `techOrder` option. Use it to tell videojs loads which kind of tech sources(flash, html5).
`videojs-contrib-dash` just register `DashSourceHandle` to `video.js`
